print       ('"Nothing \nwill work \nunless you do')
print ('   Anyone who')
print ('      stops')
print ('         learning is old')
print ('            whether at twenty or eighty"')
print ('                       Henry Ford')