print('     "Life is what happens')
print('             when')
print("                 you're busy")
print('                         making other plans"')    
print('                                          John Lennon.')
